### ISSUE TITLE
If no wifi adapter is available, then the setup fails

### ISSUE THREAD

**Issue by dhylands** [mozilla-iot/gateway-wifi-setup#26]
I tried to run our image on my Raspberry Pi 2 which doesn't have Wifi (but did have hard wired ethernet). I checked the gateway-wifi-setup-app.log file and it contained the following:
```
nvm version
0.33.1
node version
v7.10.1
npm version
4.2.0
Starting wifi service  ...

> vaani.setup@0.0.1 start /root/gateway-wifi-setup
> node index.js

starting the wifi server
check 1
Running command: wpa_cli -iwlan0 status | sed -n -e '/^wpa_state=/{s/wpa_state=//;p;q}'
HTTP server listening
Command wrote to stderr, assuming failure: Failed to connect to non-global ctrl_ifname: wlan0  error: No such file or directory

Error checking wifi on attempt 1 : Error: wpa_cli -iwlan0 status | sed -n -e '/^wpa_state=/{s/wpa_state=//;p;q}' output to stderr: Failed to connect to non-global ctrl_ifname: wlan0  error: No such file or directory

    at /root/gateway-wifi-setup/run.js:23:16
    at ChildProcess.exithandler (child_process.js:197:7)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:194:7)
    at maybeClose (internal/child_process.js:899:16)
    at Socket.<anonymous> (internal/child_process.js:342:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at Pipe._handle.close [as _onclose] (net.js:511:12)
check 2
Running command: wpa_cli -iwlan0 status | sed -n -e '/^wpa_state=/{s/wpa_state=//;p;q}'
Command wrote to stderr, assuming failure: Failed to connect to non-global ctrl_ifname: wlan0  error: No such file or directory

Error checking wifi on attempt 2 : Error: wpa_cli -iwlan0 status | sed -n -e '/^wpa_state=/{s/wpa_state=//;p;q}' output to stderr: Failed to connect to non-global ctrl_ifname: wlan0  error: No such file or directory

    at /root/gateway-wifi-setup/run.js:23:16
    at ChildProcess.exithandler (child_process.js:197:7)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:194:7)
    at maybeClose (internal/child_process.js:899:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
check 3
Running command: wpa_cli -iwlan0 status | sed -n -e '/^wpa_state=/{s/wpa_state=//;p;q}'
Command wrote to stderr, assuming failure: Failed to connect to non-global ctrl_ifname: wlan0  error: No such file or directory
```
After about 20 repeats, it then started to give:
```
check 20
Running command: wpa_cli -iwlan0 status | sed -n -e '/^wpa_state=/{s/wpa_state=//
/;p;q}'
Command wrote to stderr, assuming failure: Failed to connect to non-global ctrl__
ifname: wlan0  error: No such file or directory

Error checking wifi on attempt 20 : Error: wpa_cli -iwlan0 status | sed -n -e '//
^wpa_state=/{s/wpa_state=//;p;q}' output to stderr: Failed to connect to non-gloo
bal ctrl_ifname: wlan0  error: No such file or directory

    at /root/gateway-wifi-setup/run.js:23:16
    at ChildProcess.exithandler (child_process.js:197:7)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:194:7)
    at maybeClose (internal/child_process.js:899:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
Giving up. No wifi available.
error starting wifi: undefined
startAP
Running command: iwlist wlan0 scan |sed -n -e '
  /Quality=/,/ESSID:/H
  /ESSID:/{
    g
    s/^.*Quality=\([0-9]\+\).*Encryption key:\([a-z]\+\).*ESSID:"\([^"]*\)".*$/\1 \2  \3/
    p
    s/.*//
    x
  }' |sort -nr
Command wrote to stderr, assuming failure: wlan0     Interface doesn't support scanning.


Scan attempt 1 failed: iwlist wlan0 scan |sed -n -e '
  /Quality=/,/ESSID:/H
  /ESSID:/{
    g
    s/^.*Quality=\([0-9]\+\).*Encryption key:\([a-z]\+\).*ESSID:"\([^"]*\)".*$/\1 \2  \3/
    p
    s/.*//
    x
  }' |sort -nr output to stderr: wlan0     Interface doesn't support scanning.


Will try again in 3 seconds.
```
that eventually gave up and then we get this:
```
Giving up. No scan results available.
Running command: ifconfig wlan0 10.0.0.1 && systemctl start hostapd && systemctl start dnsmasq
Error running command: { Error: Command failed: ifconfig wlan0 10.0.0.1 && systemctl start hostapd && systemctl start dnsmasq
SIOCSIFADDR: No such device
wlan0: ERROR while getting interface flags: No such device

    at ChildProcess.exithandler (child_process.js:205:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:194:7)
    at maybeClose (internal/child_process.js:899:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
  killed: false,
  code: 255,
  signal: null,
  cmd: 'ifconfig wlan0 10.0.0.1 && systemctl start hostapd && systemctl start dnsmasq' }
(node:779) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Command failed: ifconfig wlan0 10.0.0.1 && systemctl start hostapd && systemctl start dnsmasq
SIOCSIFADDR: No such device
wlan0: ERROR while getting interface flags: No such device

(node:779) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
handleCaptive /
skipping.
Running command: wpa_cli -iwlan0 status | sed -n -e '/^wpa_state=/{s/wpa_state=//;p;q}'
Command wrote to stderr, assuming failure: Failed to connect to non-global ctrl_ifname: wlan0  error: No such file or directory

Error: wpa_cli -iwlan0 status | sed -n -e '/^wpa_state=/{s/wpa_state=//;p;q}' output to stderr: Failed to connect to non-global ctrl_ifname: wlan0  error: No such file or directory

    at /root/gateway-wifi-setup/run.js:23:16
    at ChildProcess.exithandler (child_process.js:197:7)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:194:7)
    at maybeClose (internal/child_process.js:899:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
```

Attermpting to connect to http://gateway.local then gave this output
```
handleCaptive /
skipping.
Running command: wpa_cli -iwlan0 status | sed -n -e '/^wpa_state=/{s/wpa_state=//;p;q}'
Command wrote to stderr, assuming failure: Failed to connect to non-global ctrl_ifname: wlan0  error: No such file or directory

Error: wpa_cli -iwlan0 status | sed -n -e '/^wpa_state=/{s/wpa_state=//;p;q}' output to stderr: Failed to connect to non-global ctrl_ifname: wlan0  error: No such file or directory

    at /root/gateway-wifi-setup/run.js:23:16
    at ChildProcess.exithandler (child_process.js:197:7)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:194:7)
    at maybeClose (internal/child_process.js:899:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
```
and the browser just spins.
Attempting to attach to gateway.local

**Comment by andrenatal** [comment]
fixed by #31
