### ISSUE TITLE
setup fails when there is no wifi adapter

### ISSUE THREAD

**Issue by dhylands** [mozilla-iot/gateway-wifi-setup#47]
If I try to boot the latest wifi setup code on a Raspberry Pi 2 which has no wifi adapter, then I get the following error:
```
nvm version
0.33.1
node version
v7.10.1
npm version
4.2.0
Starting wifi service  ...

> gateway-wifi-setup@0.0.1 start /root/gateway-wifi-setup
> node index.js

starting the wifi server
Running command: wpa_cli -iwlan0 status | sed -n -e '/^wpa_state=/{s/wpa_state=//;p;q}'
HTTP server listening
Command wrote to stderr, assuming failure: Failed to connect to non-global ctrl_ifname: wlan0  error: No such file or directory

Error checking wifi adapter presence. Start the gateway and then shutdown the wifi service.. Error: wpa_cli -iwlan0 status | sed -n -e '/^wpa_state=/{s/wpa_state=//;p;q}' output to stderr: Failed to connect to non-global ctrl_ifname: wlan0  error: No such file or directory

    at /root/gateway-wifi-setup/run.js:23:16
    at ChildProcess.exithandler (child_process.js:197:7)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:194:7)
    at maybeClose (internal/child_process.js:899:16)
    at Socket.<anonymous> (internal/child_process.js:342:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at Pipe._handle.close [as _onclose] (net.js:511:12)
start the gateway
Running command: systemctl start mozilla-iot-gateway
stop wifi setup
Running command: systemctl stop mozilla-gateway-wifi-setup
```

**Comment by andrenatal** [comment]
But isn't this the expected behavior like mentioned [here](https://github.com/mozilla-iot/gateway-wifi-setup/issues/26)? 

The setup isn't failing. It ends gracefully starting the gateway and shutting down the wifi setup. See the last two lines:
`start the gateway
Running command: systemctl start mozilla-iot-gateway
stop wifi setup
Running command: systemctl stop mozilla-gateway-wifi-setup`

If this isn't the expected behavior, then what the wifi-setup should do when the device has no wifi?
